moveit_controller_manager: moveit_ros_control_interface/MoveItControllerManager

moveit_ros_control_interface:
  ros__parameters:

    robot_description: ""
    
    # Lista de controladores que o MoveIt pode usar 
    controller_names:
      - arm_controller
      - gripper_controller
    
    # Configuração do controlador do braço
    arm_controller:
      type: FollowJointTrajectory
      default: true
      action_ns: follow_joint_trajectory
      joints:
        - waist_joint
        - shoulder_pitch_joint
        - elbow_pitch_joint
        - wrist_pitch_joint
        
    # Configuração do controlador da garra
    gripper_controller:
      type: FollowJointTrajectory
      default: true
      action_ns: follow_joint_trajectory
      joints:
        - gripper_finger_joint