<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="M_PI" value="3.14159"/>
  <xacro:property name="SCALE_MM" value="0.001"/>
  <xacro:property name="SCALE_CM" value="0.01"/>

  <xacro:property name="AX12_WIDTH" value="0.032"/>
  <xacro:property name="AX12_ORIGIN_TO_SIDE_SCREW" value="0.0135"/>
  <xacro:property name="AX12_ORIGIN_OFFSET_X" value="-0.0015"/>
  <xacro:property name="AX12_SIDE_SCREW_OFFSET" value="0.0028"/>
  <xacro:property name="AX12_LENGTH" value="0.050"/>
  <xacro:property name="AX12_ORIGIN_TO_END_SCREW" value="0.024"/>
  <xacro:property name="AX12_AXLE_OFFSET" value="0.0135"/>
  <xacro:property name="AX12_ORIGIN_TO_AXLE" value="0.012"/>
  <xacro:property name="AX12_HEIGHT" value="0.040"/>
  <xacro:property name="AX12_BODY_MAIN_HEIGHT" value="0.032"/>
  <xacro:property name="AX12_BODY_FULL_HEIGHT" value="0.038"/>
  <xacro:property name="AX12_HORN_HEIGHT" value="0.021"/>

  <xacro:property name="F2_HEIGHT" value="0.0375"/>
  <xacro:property name="F2_AXLE_HEIGHT" value="0.0265"/>
  <xacro:property name="F3_SCREW_HEIGHT" value="0.0055"/>
  <xacro:property name="F4_HEIGHT" value="0.065"/>
  <xacro:property name="F4_AXLE_HEIGHT" value="0.0525"/>
  <xacro:property name="F53_HEIGHT" value="0.007"/>
  <xacro:property name="MOUNT_HEIGHT" value="0.001"/>

  <xacro:macro name="dynamixel_ax12_fixed" params="parent name color *origin">
    <joint name="${name}_joint" type="fixed"><xacro:insert_block name="origin"/><parent link="${parent}"/><child link="${name}_link"/></joint>
    <link name="${name}_link">
      <inertial><mass value="0.055"/><origin xyz="0 0 0"/><inertia ixx="1.7e-5" ixy="0" ixz="0" iyy="1.3e-5" iyz="0" izz="9.4e-6"/></inertial>
      <visual><origin xyz="0 0 0" rpy="-${M_PI/2} 0 0"/><geometry><mesh filename="package://arm_description/meshes/crane_plus_ax12.stl" scale="${SCALE_MM} ${SCALE_MM} ${SCALE_MM}"/></geometry><material name="${color}"/></visual>
      <collision><origin xyz="${0-AX12_ORIGIN_OFFSET_X} 0 0" rpy="0 0 0"/><geometry><box size="${AX12_LENGTH} ${AX12_WIDTH} ${AX12_BODY_FULL_HEIGHT}"/></geometry></collision>
    </link>
  </xacro:macro>

  <xacro:macro name="bioloid_f2_revolute" params="parent name color llimit ulimit vlimit *origin">
    <joint name="${name}_joint" type="revolute"><xacro:insert_block name="origin"/><axis xyz="0 -1 0"/><limit effort="30" velocity="${vlimit}" lower="${llimit}" upper="${ulimit}"/><parent link="${parent}"/><child link="${name}_link"/></joint>
    <link name="${name}_link">
      <inertial><mass value="0.01"/><origin xyz="0 0 -${F2_AXLE_HEIGHT-F2_HEIGHT/2}" rpy="0 0 0"/><inertia ixx="2.2e-6" ixy="0" ixz="0" iyy="2.4e-6" iyz="0" izz="8.1e-7"/></inertial>
      <visual><origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/><geometry><mesh filename="package://arm_description/meshes/f2.stl" scale="${SCALE_MM} ${SCALE_MM} ${SCALE_MM}"/></geometry><material name="${color}"/></visual>
      <collision><origin xyz="0 0 -${F2_AXLE_HEIGHT-F2_HEIGHT/2}" rpy="0 0 0"/><geometry><box size="0.025 0.0485 0.0375"/></geometry></collision>
    </link>
  </xacro:macro>

  <xacro:macro name="bioloid_f3_fixed" params="parent name color *origin">
    <joint name="${name}_joint" type="fixed"><xacro:insert_block name="origin"/><parent link="${parent}"/><child link="${name}_link"/></joint>
    <link name="${name}_link">
      <inertial><mass value="0.005"/><origin xyz="0 0 0.0045" rpy="0 0 0"/><inertia ixx="6.3e-7" ixy="0" ixz="0" iyy="8.6e-7" iyz="0" izz="2.9e-7"/></inertial>
      <visual><origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI}"/><geometry><mesh filename="package://arm_description/meshes/f3.stl" scale="${SCALE_MM} ${SCALE_MM} ${SCALE_MM}"/></geometry><material name="${color}"/></visual>
      <collision><origin xyz="0 0 0.0045" rpy="0 0 0"/><geometry><box size="0.025 0.038 0.009"/></geometry></collision>
    </link>
  </xacro:macro>

  <xacro:macro name="fixed_finger" params="parent name color *origin">
    <joint name="${name}_joint" type="fixed"><xacro:insert_block name="origin"/><parent link="${parent}"/><child link="${name}_link"/></joint>
    <link name="${name}_link">
      <inertial><mass value="0.02"/><origin xyz="0 0 0" rpy="0 0 0"/><inertia ixx="1.6e-5" ixy="0" ixz="0" iyy="1.8e-5" iyz="0" izz="2.7e-6"/></inertial>
      <visual><origin xyz="0 0 0" rpy="0 0 0"/><geometry><mesh filename="package://arm_description/meshes/finger_fixed.stl" scale="${SCALE_MM} ${SCALE_MM} ${SCALE_MM}"/></geometry><material name="${color}"/></visual>
      <collision><origin xyz="0 0 0" rpy="0 0 0"/><geometry><mesh filename="package://arm_description/meshes/finger_fixed_collision.stl" scale="${SCALE_MM} ${SCALE_MM} ${SCALE_MM}"/></geometry></collision>
    </link>
  </xacro:macro>

  <xacro:macro name="moving_finger" params="parent name color *origin">
    <joint name="${name}_joint" type="fixed"><xacro:insert_block name="origin"/><parent link="${parent}"/><child link="${name}_link"/></joint>
    <link name="${name}_link">
      <inertial><mass value="0.02"/><origin xyz="0 0 0" rpy="0 0 0"/><inertia ixx="2.0e-5" ixy="0" ixz="0" iyy="2.2e-5" iyz="0" izz="2.9e-6"/></inertial>
      <visual><origin xyz="0 0 0" rpy="0 0 0"/><geometry><mesh filename="package://arm_description/meshes/finger_moving.stl" scale="${SCALE_MM} ${SCALE_MM} ${SCALE_MM}"/></geometry><material name="${color}"/></visual>
      <collision><origin xyz="0 0 0" rpy="0 0 0"/><geometry><mesh filename="package://arm_description/meshes/finger_moving_collision.stl" scale="${SCALE_MM} ${SCALE_MM} ${SCALE_MM}"/></geometry></collision>
    </link>
  </xacro:macro>

  <xacro:macro name="custom_finger" params="parent name color *origin">
    <joint name="${name}_joint" type="fixed"><xacro:insert_block name="origin"/><parent link="${parent}"/><child link="${name}_link"/></joint>
    <link name="${name}_link">
      <inertial><mass value="0.01"/><origin xyz="0 0 0"/><inertia ixx="1.0e-5" ixy="0" ixz="0" iyy="1.0e-5" iyz="0" izz="1.0e-5"/></inertial>

      <visual>
        <origin xyz="0.05 0 0" rpy="0 0 0"/> 
        <geometry><mesh filename="package://arm_description/meshes/garra.stl" scale="${SCALE_MM} ${SCALE_MM} ${SCALE_MM}"/></geometry>
        <material name="${color}"/>
      </visual>

      <collision>
        <origin xyz="0.05 0 0" rpy="0 0 0"/>
        <geometry><mesh filename="package://arm_description/meshes/garra.stl" scale="${SCALE_MM} ${SCALE_MM} ${SCALE_MM}"/></geometry>
      </collision>

    </link>
  </xacro:macro>

  
</robot>